### ISSUE TITLE
Typo in dependencies

### ISSUE THREAD

**Issue by rastio** [onkelbeh/HomeAssistantRepository#25]
Hello Andreas,

there is a typo in the dependencies for 0.115.6 - there should be underscore instead of hyphen in dev-python/importlib_metadata-1.6.0, i.e. dev-python/importlib_underscore_metadata-1.6.0.

https://github.com/onkelbeh/HomeAssistantRepository/blob/3a522279f327d0c90e62bba10ecd93532e2e3661/app-misc/homeassistant/homeassistant-0.115.6.ebuild#L65

Thanks for your work

All the best

Rasto

**Comment by onkelbeh** [comment]
Yep, you are right, thanks for reporting,
unfortunately it is not a typo, the main Ebuilds are generated since 0.115,
looks like i forgot the package name substitution in the gen_cond_dep subroutine,
writing this part I was too focused on setting correct escape for the f-String.
I did not sense it during tests because all test boxes run 3.8 already and the 3.7 box is not on the new repo yet.

I will look into it before 0.116.0_beta1
:-) you should upgrade

**Comment by onkelbeh** [comment]
For now, I replace the string: https://github.com/onkelbeh/HomeAssistantRepository/commit/8c2727678163a8095a5ffab80d5cd72cb401275e
I'll leave the ticket open until the build script is fixed.

**Comment by onkelbeh** [comment]
Yeah, and the 3.7 box still has the old `importlib-metadata` installed, which was removed as a dupe on 2020-04-13.

**Comment by onkelbeh** [comment]
just added forgotten check_pkg_subst() for python_gen_cond_dep constraints in the build script.
Don't forget to star this repo :-)
