### ISSUE TITLE
bt_proximity - missing pybluez dependency

### ISSUE THREAD

**Issue by denilsonsa** [onkelbeh/HomeAssistantRepository#39]
Hi! The `dev-python/bt-proximity` ebuild is missing a dependency on `dev-python/pybluez`.

Sure, most people using this overlay will install a bunch of other packages that will end up pulling pybluez. In my case, I enabled the overlay just because I wanted to try one single package, and got surprised when it didn't work.

**Comment by onkelbeh** [comment]
bt-proximity simply is not pulling pybluez (see https://github.com/FrederikBolding/bluetooth-proximity/blob/master/setup.py)
we use strict the requirements a package is using, no matter how stupid, especially on hard pinned versions.

The fix is simple: install both packages as @FrederikBolding explains in his [README.md](https://github.com/FrederikBolding/bluetooth-proximity/blob/master/README.md)

**Comment by FrederikBolding** [comment]
Yeah, it is required as part of the HA config here: https://github.com/home-assistant/core/blob/dev/homeassistant/components/bluetooth_tracker/manifest.json

But I guess the package itself never required it. I don't particularly remember the reason, might also be an oversight from the project I forked.

**Comment by onkelbeh** [comment]
Yes, thats the way it's corrctly pulled in, done by the [main Ebuild](https://github.com/onkelbeh/HomeAssistantRepository/blob/master/app-misc/homeassistant/homeassistant-2021.7.3.ebuild), look at line 161, but not from the component itself.
Sorry, but I have to stay very precise here, managing a Repo for Home Assistant with currently 1008 components and 1946 packages.

**Comment by onkelbeh** [comment]
If @FrederikBolding adds it to his requirements, it can be removed from `bluetooth_tracker`'s manifest.json. Then we could add it as a RDEPEND to the Ebuild. I would suggest doing so, because running `bt_proximity` without `pybluez` does not make any sense.
