### ISSUE TITLE
Update some dependencies

### ISSUE THREAD

**Issue by RayOfLight1** [onkelbeh/HomeAssistantRepository#45]
Hey, I'm having warnings of portage trying to update pip and pillow to the latest stable amd64 versions, and the ebuilds from homeassitant-min not letting it do so, it seems that HA requires pip to be <20.3.0 when that version is not on the main tree anymore, also it requires pillow to be ~8.2.0 when we have newer stable versions.

Can you unlock such limits in the ebuild? Is there any reason to cap HA to those specific versions? Regards,

**Comment by onkelbeh** [comment]
Nope, sorry, can't do that, requirements are taken by an automated routine from upstream. There _could_ be reasons why these are sometimes not at the current version, and don't have the capacity to do the necessary tests. Many fixed dependencies (necessary or not) to old releases forbid installation of packages requiring newer ones, but I filed all dependencies strict as they have been declared in setup.py or requirements.txt (sometimes other sources) anyway. The exception proves the rule. Could be that there is no 'real' reason for this older stuff, some components @ Home Assistant are not very well maintained.

Back to your examples:
e.g. dev-python/pip: taken from https://github.com/home-assistant/core/blob/dev/requirements.txt, an appropriate version lives in [this repo](https://git.edevau.net/onkelbeh/HomeAssistantRepository/src/branch/master/dev-python/pip).
dev-python/pillow: taken from https://github.com/home-assistant/core/blob/dev/requirements_all.txt 

There are some exceptions (where I take the time to do the tests, mostly for packages I use very frequently, for example dev-embedded/esphome, and some dev (-9999) Ebuilds. In these cases I added small patches to the Ebuilds, because some packages have versions pinned obviously without any reason. Mostly, I copy hard pinnings without questioning, in very problematic cases I open a ticket at the problem's origin. For me its OK, if the packages compile and complete their own tests in the sandbox.

You could file an issue or a pull request at https://github.com/home-assistant/core. Sometimes pinned versions disappear from the main repo, in this case, please file an issue (or PR) here (or better [here](https://git.edevau.net/onkelbeh/HomeAssistantRepository/issues)), I will then re-add a copy from main repo's archive.

I run Home Assistant in a [dedicated box](https://github.com/onkelbeh/HomeAssistantRepository#my-vmsboxes-and-stuff-i-use), where I can (and have to) live with these versions.

**Comment by onkelbeh** [comment]
PS: I can respond faster on issues opened at [my own git server](https://git.edevau.net/onkelbeh/HomeAssistantRepository/issues). I only come here for releases.

**Comment by onkelbeh** [comment]
Did a brief re-check, (old) [pip-20.2.4](https://github.com/onkelbeh/HomeAssistantRepository/commit/07550b133ffa316dd1b84eccb06983db3267c14d) would also match all constraints, but still is vulnerable to CVE-2021-3572. Just bumped it. Better than nothing.
